platform: linux
image_resource:
  type: docker-image
inputs:
  - name: bin_gpdb
  - name: diskquota_src
  - name: gpdb_src
  - name: bin_cmake
  - name: last_released_diskquota_bin

outputs:
  - name: diskquota_artifacts

run:
  path: diskquota_src/concourse/scripts/entry.sh
  args:
    - build
params:
  DISKQUOTA_OS:
  BUILD_TYPE:
