#ifdef DB_STATUS
DB_STATUS(DB_STATUS_UNKNOWN = 0, "UNKNOWN")
DB_STATUS(DB_INIT, "INIT")
DB_STATUS(DB_ERROR, "ERROR")
DB_STATUS(DB_UNREADY, "UNREADY")
DB_STATUS(DB_PAUSED, "PAUSED")
DB_STATUS(DB_RUNNING, "RUNNING")
#endif
