name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - hy/actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: greenplum-db/gpdb
          ref: 6X_STABLE 
      - name: Set env
        run: |
          sudo tee -a /etc/sysctl.conf << EOF
          kernel.shmmax = 5000000000000
          kernel.shmmni = 32768
          kernel.shmall = 40000000000
          kernel.sem = 1000 32768000 1000 32768
          kernel.msgmnb = 1048576
          kernel.msgmax = 1048576
          kernel.msgmni = 32768
          net.core.netdev_max_backlog = 80000
          net.core.rmem_default = 2097152
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          vm.overcommit_memory = 2
          vm.overcommit_ratio = 95
          EOF
          sudo sysctl -p
          sudo mkdir -p /etc/security/limits.d
          sudo tee -a /etc/security/limits.d/90-greenplum.conf << EOF
          * soft nofile 1048576
          * hard nofile 1048576
          * soft nproc 1048576
          * hard nproc 1048576
          EOF
          ulimit -n 65536 65536
           
      - name: Compile
        run: |
          sudo apt-get update
          sudo ./README.ubuntu.bash
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ./configure --with-python --disable-orca --disable-gpcloud --with-gssapi --prefix=/home/runner/.local/gpdb
          make -j8 && make -j8 install
      - name: Run GPDB 
        run: |
          export GPHOME=/home/runner/.local/gpdb
          export PYTHONPATH="${GPHOME}/lib/python"
          export PATH="${GPHOME}/bin:${PATH}"
          export LD_LIBRARY_PATH="${GPHOME}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
          export OPENSSL_CONF="${GPHOME}/etc/openssl.cnf"
          make create-demo-cluster
