name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - hy/actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: greenplum-db/gpdb
          ref: 6X_STABLE 
      - name: Compile
        run: |
          sudo apt-get update
          sudo ./README.ubuntu.bash
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ./configure --with-python --disable-orca  --disable-gpcloud --with-gssapi --prefix=/usr/local/gpdb
          sudo make -j8
          sudo make -j8 install
          . /usr/local/gpdb/greenplum_path.sh
          sudo make create-demo-cluster
