name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - hy/actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: greenplum-db/gpdb
          ref: 6X_STABLE 
      - name: Compile
        run: |
          sudo apt-get update
          sudo ./README.ubuntu.bash
          ssh-keygen
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb
          make -j8
          make -j8 install
          source /usr/local/gpdb/greenplum_path.sh
          make create-demo-cluster
