name: Test

on:
  push:
    branches:
      - hy/actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout gpdb
        uses: actions/checkout@v3
        with:
          repository: greenplum-db/gpdb
      - name: Set env
        run: |
          sudo tee -a /etc/sysctl.conf << EOF
          kernel.shmmax = 5000000000000
          kernel.shmmni = 32768
          kernel.shmall = 40000000000
          kernel.sem = 1000 32768000 1000 32768
          kernel.msgmnb = 1048576
          kernel.msgmax = 1048576
          kernel.msgmni = 32768
          net.core.netdev_max_backlog = 80000
          net.core.rmem_default = 2097152
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          vm.overcommit_memory = 2
          vm.overcommit_ratio = 95
          EOF
          sudo sysctl -p
          sudo mkdir -p /etc/security/limits.d
          sudo tee -a /etc/security/limits.d/90-greenplum.conf << EOF
          * soft nofile 1048576
          * hard nofile 1048576
          * soft nproc 1048576
          * hard nproc 1048576
          EOF
          ulimit -n 65536 65536
      - name: Compile
        run: |
          sudo apt-get update
          sudo apt-get install libipc-run-perl clang llvm
          
          sudo ./README.Ubuntu.bash
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          mkdir -p ~/.ssh     
          echo "Host *" > ~/.ssh/config     
          echo " StrictHostKeyChecking no" >> ~/.ssh/config
          ./configure --with-python --disable-orca --disable-gpcloud  --with-gssapi --disable-cassert --enable-tap-tests --with-zstd --with-llvm --with-libxml --prefix=/home/runner/.local/gpdb
          make -j8 && make install

      - name: Install python package
        run: |
          pip3 install -r python-dependencies.txt
          pip3 install cmake

      - name: Run GPDB 
        run: |
          source /home/runner/.local/gpdb/greenplum_path.sh
          LANG=en_US.utf8 make create-demo-cluster
      - name: Check Run
        run: |
          source /home/runner/.local/gpdb/greenplum_path.sh 
          source gpAux/gpdemo/gpdemo-env.sh
          psql -p 7000 postgres -c 'select version();'

      - name: Checkout diskquota 
        uses: actions/checkout@v3
      
      - name: diskquota
        run: |
          pwd
          source /home/runner/.local/gpdb/greenplum_path.sh 
          source /home/runner/work/gpdb/gpdb/gpAux/gpdemo/gpdemo-env.sh
          mkdir build
          cd build
          cmake ..
          make
          make install
          gpconfig -c shared_preload_libraries -v 'diskquota-2.2'
          gpstop -ar
          make installcheck

      - name: Setup upterm session
        if: ${{  failure() }}
        uses: lhotari/action-upterm@v1
 
      - name: Check diff
        if: ${{  failure() }}
        run: | 
          cat /home/runner/work/gpdb/gpdb/src/test/regress/regression.diffs