name: Test

on:
  push:
    branches:
      - hy/actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 0
        uses: actions/checkout@v2
      - name: run setup runner
        run: |
          .github/workflows/scripts/setup.sh
      - name: Checkout 1
        uses: actions/checkout@v3
        with:
          repository: greenplum-db/gpdb
          ref: 6X_STABLE 
      - name: Set env
        run: |
          sudo tee -a /etc/sysctl.conf << EOF
          kernel.shmmax = 5000000000000
          kernel.shmmni = 32768
          kernel.shmall = 40000000000
          kernel.sem = 1000 32768000 1000 32768
          kernel.msgmnb = 1048576
          kernel.msgmax = 1048576
          kernel.msgmni = 32768
          net.core.netdev_max_backlog = 80000
          net.core.rmem_default = 2097152
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          vm.overcommit_memory = 2
          vm.overcommit_ratio = 95
          EOF
          sudo sysctl -p
          sudo mkdir -p /etc/security/limits.d
          sudo tee -a /etc/security/limits.d/90-greenplum.conf << EOF
          * soft nofile 1048576
          * hard nofile 1048576
          * soft nproc 1048576
          * hard nproc 1048576
          EOF
          ulimit -n 65536 65536
      - name: Setup Up gpadmin
        run: |
          echo test
      - name: Compile
        run: |
          sudo apt-get update
          sudo ./README.ubuntu.bash
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          mkdir -p ~/.ssh     
          echo "Host *" > ~/.ssh/config     
          echo " StrictHostKeyChecking no" >> ~/.ssh/config
          ./configure --with-python --disable-orca --disable-gpcloud  --without-zstd --with-gssapi --prefix=/home/runner/.local/gpdb
          make -j8 && make -j8 install

      - name: Run GPDB 
        run: |
          source /home/runner/.local/gpdb/greenplum_path.sh
          make create-demo-cluster
